[package]
edition = "2021"
name = "tomato"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.3.10", features = ["derive"]}
humantime = "2.1.0"
indicatif = "0.17.5"
